FROM progrium/busybox

RUN opkg-install nginx curl

RUN mkdir /var/lib/nginx

ADD nginx.conf /etc/nginx/nginx.conf

ADD run.sh /usr/local/bin/run.sh

RUN curl -ksL https://github.com/pixelpark/ppnet/archive/master.tar.gz | gunzip | tar -x -C /usr

EXPOSE 80

CMD ["/usr/local/bin/run.sh"]
